version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content/themes/rbfresh:/var/www/html/wp-content/themes/rbfresh
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
    networks:
      - wpsite

  # Node.js container for SASS compilation (optional)
  node:
    image: node:18
    volumes:
      - ./wp-content/themes/rbfresh:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm run sass"
    networks:
      - wpsite

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  wpsite:
